### ISSUE TITLE
hideCloseButton

### ISSUE THREAD

**Issue by haizen007** [SimonDMC/popup-js#3] opened 2024-06-03 19:31 UTC
hideCloseButton: false,
doesn't work, it never shows the button and if
allowClose: true,
doesn't matter since it will close automatically
I think was supposed to be the opposite behavior?

**Comment by SimonDMC** [comment] 2024-06-03 19:42
hey hey, could you provide an example of the code you're running? if i pass in `hideCloseButton: false` it displays the close button as intended (default behavior). also i'm not sure what you mean by the allowClose thing, it's closable by default but you can set it to true to prevent the user from closing it manually

**Comment by haizen007** [comment] 2024-06-03 19:55
but if I prevent it from closing it doesn't show the button to close.
			
	                        hideTitle: false,
				allowClose: true,
				hideCloseButton: false,

then without button

				hideTitle: false,
				allowClose: true,
				hideCloseButton: false,

**Comment by haizen007** [comment] 2024-06-03 19:57
btw, I'm trying to create a button to copy the content of a variable since just showing the content didn't work well because it was overflowing the popup size.

**Comment by SimonDMC** [comment] 2024-06-03 20:01
> but if I prevent it from closing it doesn't show the button to close.
> 
> ```
>                         hideTitle: false,
> 			allowClose: true,
> 			hideCloseButton: false,
> ```
> 
> then without button
> 
> ```
> 			hideTitle: false,
> 			allowClose: true,
> 			hideCloseButton: false,
> ```

huh? you're leaving all the values as default - not hiding the title, not preventing the popup from closing and not hiding the close button. it works fine for me https://jsfiddle.net/hud2n0ex/ also you pasted the same snippet twice
![image](https://github.com/SimonDMC/popup-js/assets/46278840/151e1dd0-1e8d-415c-a99b-a21553cb9f34)

**Comment by haizen007** [comment] 2024-06-03 22:24
I guess I expected a different behavior, I thought that with the close button it would prevent it from naturally closing if I click outside the popup, otherwise makes no sense for me to have the button at all.
Btw, is it possible to call a func when I click on the button?

https://jsfiddle.net/cLe17r6u/

EDIT

> 				loadCallback: () => {
> 					document.querySelector(".popup.pix button").addEventListener("click", () => {
> 						navigator.clipboard.writeText(result);
> 					});
> 				},
> 			});

maybe I'm doing something wrong but it copies once, if I open the popup again and result has changed it wont copy again...

**Comment by SimonDMC** [comment] 2024-06-04 14:12
well the point is that you can close the popup one of many different ways - click the close button, click outside or press the escape key. it's just supposed to make it more intuitive. as for the copying, again, works fine for me - the jsfiddle you sent has a wrong querySelector so it doesn't work at all but I made you an example where it does work. put anything into the input and then the copy button in the popup copies it (even if the variable changes) https://jsfiddle.net/mqy9zjk7/

**Comment by haizen007** [comment] 2024-06-06 18:56
ok, thanks

**Closed as completed** 2024-06-16 12:55 UTC
